# Generated by Django 4.1.7 on 2023-03-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='predictor.predictionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('percentage', models.FloatField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='predictor.predictionresult')),
            ],
        ),
    ]
