# Generated by Django 4.1.7 on 2023-03-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="meachine_learning_models")),
                ("name", models.CharField(max_length=255)),
                ("acc", models.FloatField(default=0)),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
