# Generated by Django 4.1.7 on 2023-03-24 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expert", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModelActivation",
            new_name="MechineLearningModel",
        ),
    ]
